{% set name = "tkwant" %}
{% set version = "1.1.0rc2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.kwant-project.org/kwant/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 6c869c022ddff6828f227c488bba9eda6ac92eb73176a02e9289461a63178be9
  patches:
    - requirement_patch.diff

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - libblas
    - libcblas
    - cython
    - python
    - numpy
    - scipy
    - pytest-runner
    - python
    # Pin the Python version to 3.8 for OSX
    - python >=3.8,<3.9 [target_platform=osx-64]
    # Other platforms (Linux and Windows) have no restrictions
    - python [not target_platform=osx-64]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython
    - scipy
    - pytest
    - sympy
    - tinyarray
    - mpmath
    - matplotlib-base
    - kwant
    - kwantspectrum
    - mpi4py

test:
  imports:
    - tkwant
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://tkwant.kwant-project.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Tkwant can simulate time-dependent quantum dynamics of mesoscopic systems.
  description: |
    Tkwant is a python package to simulate time-dependent quantum dynamics of
    mesoscopic systems. It is the time-dependent generalization of the
    Kwant package and distributed under 2-clause BSD license.
  doc_url: https://tkwant.kwant-project.org/doc/stable/
  dev_url: https://gitlab.kwant-project.org/kwant/tkwant/

extra:
  recipe-maintainers:
    - thkloss
    - basnijholt
