{% set name = "tkwant" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.kwant-project.org/kwant/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 5b0da45a1df38811632178fbddafaaa8c4da6cac97015338c6e2c47bd44d7efc
  patches:
    - requirement_patch.diff

build:
  number: 0
  skip: true  # [osx and py>38]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - libblas
    - libcblas
    - cython
    - python
    - numpy
    - scipy
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython
    - scipy
    - pytest
    - sympy
    - tinyarray
    - mpmath
    - matplotlib-base
    - kwant
    - kwantspectrum
    - mpi4py

test:
  imports:
    - tkwant
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://tkwant.kwant-project.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Tkwant can simulate time-dependent quantum dynamics of mesoscopic systems.
  description: |
    Tkwant is a python package to simulate time-dependent quantum dynamics of
    mesoscopic systems. It is the time-dependent generalization of the
    Kwant package and distributed under 2-clause BSD license.
  doc_url: https://tkwant.kwant-project.org/doc/stable/
  dev_url: https://gitlab.kwant-project.org/kwant/tkwant/

extra:
  recipe-maintainers:
    - thkloss
    - basnijholt
